import { useCallback, useEffect, useMemo, useRef, useState } from 'react';

import {
  getOpportunityCandidates,
  getOpportunityCandidateDetail,
  type CandidateEntryLane,
  type CandidateEntryPosture,
  type CandidateExtensionRisk,
  type CandidateItem,
  type CandidateListItem,
  type CandidateRiskMode,
  type CandidateStage,
  type CandidateTechnicalSetup,
  type OpportunityCandidateResponse,
} from '../api/opportunityCandidates';
import type {
  CandidateStrategyResponse,
  StrategyAssessment,
  StrategyChannel,
  StrategyChannelStatus,
  StrategyEvidence,
} from '../api/candidateStrategies';
import { strategyMethod, strategyScoreBreakdown } from '../api/candidateStrategyMethods';
import { useI18n, type Translate } from '../i18n/I18nProvider';
import { localizeClientError, universeName } from '../i18n/domain';

type LoadState = { kind: 'loading' } | { kind: 'error'; message: string } | { kind: 'ready'; data: OpportunityCandidateResponse };
type StageFilter = 'active' | CandidateStage | 'all';
type CandidateView = 'entry' | 'leadership' | 'strategy';
type StrategyLoadState = { kind: 'idle' } | { kind: 'loading' } | { kind: 'error'; message: string } | { kind: 'ready'; data: CandidateStrategyResponse };
const PRIMARY = 'provider_classified_common_shares_v1';
const MODES: CandidateRiskMode[] = ['conservative', 'balanced', 'aggressive'];
const VIEWS: CandidateView[] = ['entry', 'leadership', 'strategy'];
const STRATEGY_CHANNELS: StrategyChannel[] = ['momentum_breakout', 'strong_stock_pullback', 'trend_continuation', 'technical_reversal', 'fundamental_value_reversal', 'defensive_rotation'];

function requestedUniverse(): string { return new URLSearchParams(window.location.search).get('universe') ?? PRIMARY; }
function requestedMode(): CandidateRiskMode { const value = new URLSearchParams(window.location.search).get('candidateRisk'); return MODES.includes(value as CandidateRiskMode) ? value as CandidateRiskMode : 'balanced'; }
function requestedView(): CandidateView { const value = new URLSearchParams(window.location.search).get('candidateView'); return VIEWS.includes(value as CandidateView) ? value as CandidateView : 'entry'; }
function requestedStrategyChannel(): StrategyChannel { const value = new URLSearchParams(window.location.search).get('candidateStrategy'); return STRATEGY_CHANNELS.includes(value as StrategyChannel) ? value as StrategyChannel : 'momentum_breakout'; }
function writeQuery(key: string, value: string): void { const url = new URL(window.location.href); url.searchParams.set(key, value); window.history.pushState(window.history.state, '', url); }
function stageName(t: Translate, stage: CandidateStage | null): string {
  if (stage === 'watch') return t('candidate.stage.watch'); if (stage === 'prepare') return t('candidate.stage.prepare');
  if (stage === 'enter') return t('candidate.stage.enter'); if (stage === 'invalidated') return t('candidate.stage.invalidated');
  return t('candidate.stage.unavailable');
}
function componentName(t: Translate, id: string): string {
  const names: Record<string, ReturnType<Translate>> = {
    market_alignment: t('candidate.component.market'), etf_sector_alignment: t('candidate.component.etf'),
    stock_relative_strength: t('candidate.component.relative'), trend_quality: t('candidate.component.trend'),
    volume_participation: t('candidate.component.volume'), volatility_risk: t('candidate.component.volatility'),
    liquidity_suitability: t('candidate.component.liquidity'),
  }; return names[id] ?? id;
}
function laneName(t: Translate, lane: CandidateEntryLane): string { return t(`candidate.entry.lane.${lane}` as never); }
function postureName(t: Translate, posture: CandidateEntryPosture): string { return t(`candidate.entry.posture.${posture}` as never); }
function setupName(t: Translate, setup: CandidateTechnicalSetup): string { return t(`candidate.entry.setup.${setup}` as never); }
function extensionName(t: Translate, risk: CandidateExtensionRisk): string { return t(`candidate.entry.extension.${risk}` as never); }
function entryCode(t: Translate, code: string): string { return t(`candidate.entry.code.${code}` as never); }
function strategyChannelName(t: Translate, channel: StrategyChannel): string { return t(`candidate.strategy.channel.${channel}` as never); }
function strategyStatusName(t: Translate, status: StrategyChannelStatus): string { return t(`candidate.strategy.status.${status}` as never); }
function strategyCode(t: Translate, code: string): string { return t(`candidate.strategy.code.${code}` as never); }
function strategyEvidenceName(t: Translate, item: StrategyEvidence): string {
  if (item.evidence_id.startsWith('component_')) return componentName(t, item.evidence_id.replace(/^component_/, ''));
  if (item.evidence_id === 'entry_technical_setup') return t('candidate.strategy.evidence.technicalSetup');
  if (item.evidence_id === 'entry_extension_risk') return t('candidate.strategy.evidence.extensionRisk');
  return item.evidence_id;
}
function strategyEvidenceValue(t: Translate, item: StrategyEvidence): string {
  if (item.observed_value === null) return '—';
  if (item.evidence_id === 'entry_technical_setup') return setupName(t, item.observed_value as CandidateTechnicalSetup);
  if (item.evidence_id === 'entry_extension_risk') return extensionName(t, item.observed_value as CandidateExtensionRisk);
  return item.observed_value;
}
function strategyComponentName(t: Translate, id: string): string {
  return id === 'entry_geometry' ? t('candidate.strategy.evidence.entryGeometryScore') : componentName(t, id);
}
function percent(value: string | null): string { return value === null ? '—' : `${(Number(value) * 100).toFixed(1)}%`; }
function number(value: string | null, digits = 1): string { return value === null ? '—' : Number(value).toLocaleString('en-US', { maximumFractionDigits: digits }); }
function money(value: string | null): string {
  if (value === null) return '—'; const amount = Number(value);
  if (amount >= 1_000_000_000) return `$${(amount / 1_000_000_000).toFixed(1)}B`;
  if (amount >= 1_000_000) return `$${(amount / 1_000_000).toFixed(1)}M`; return `$${amount.toLocaleString('en-US', { maximumFractionDigits: 0 })}`;
}

function CandidateDetail({ item, mode, onClose }: { item: CandidateItem; mode: CandidateRiskMode; onClose: () => void }): JSX.Element {
  const { t } = useI18n(); const disposition = item.risk_dispositions.find((row) => row.risk_mode === mode); const entry = item.entry_geometry;
  const supports = item.evidence.filter((row) => row.evidence_kind === 'supporting'); const counters = item.evidence.filter((row) => row.evidence_kind === 'counterevidence');
  useEffect(() => { const key = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key); }, [onClose]);
  return <div className="candidate-drawer-backdrop" role="presentation" onMouseDown={(event) => { if (event.currentTarget === event.target) onClose(); }}><aside className="candidate-drawer" role="dialog" aria-modal="true" aria-labelledby="candidate-detail-title">
    <header><div><p className="eyebrow">{t('candidate.detailEyebrow')}</p><h2 id="candidate-detail-title">{item.ticker} · {entry ? postureName(t, entry.review_posture) : stageName(t, item.state.final_stage)}</h2><p>{item.instrument_id} · {item.security_type}</p></div><button type="button" onClick={onClose} aria-label={t('common.close')}>×</button></header>
    <div className="candidate-detail-summary"><div><span>{t('candidate.baseScore')}</span><strong>{number(item.base_score)}</strong></div><div><span>{t('candidate.dataSupport')}</span><strong>{percent(item.confidence.confidence)}</strong></div><div><span>{t('candidate.formalRank')}</span><strong>{disposition?.risk_adjusted_rank ?? t('candidate.entry.fullPool')}</strong></div><div><span>{t('candidate.latestPrice')}</span><strong>${number(item.latest_price, 2)}</strong></div></div>
    <p className="candidate-boundary">{t('candidate.researchBoundary')}</p>
    {entry ? <section className="candidate-entry-detail"><div className="candidate-entry-verdict"><span className={`candidate-entry-posture candidate-entry-posture-${entry.review_posture}`}>{postureName(t, entry.review_posture)}</span><strong>{setupName(t, entry.technical_setup)}</strong><small>{t('candidate.entry.extensionLabel')} · {extensionName(t, entry.extension_risk)}</small></div>
      <h3>{t('candidate.entry.locationTitle')}</h3><div className="candidate-facts"><span>{t('candidate.entry.sma20Distance')} <strong>{number(entry.metrics.close_to_sma_20_atr, 2)} ATR</strong></span><span>{t('candidate.entry.move5')} <strong>{number(entry.metrics.move_5_volatility_units, 2)}×</strong></span><span>{t('candidate.entry.gap')} <strong>{number(entry.metrics.current_gap_atr, 2)} ATR</strong></span><span>{t('candidate.entry.upSessions')} <strong>{entry.metrics.consecutive_up_sessions ?? '—'}</strong></span><span>{t('candidate.volumeRatio')} <strong>{number(entry.metrics.current_volume_ratio, 2)}×</strong></span><span>{t('candidate.entry.supportDistance')} <strong>{percent(entry.metrics.reference_support_distance_pct)}</strong></span></div>
      <div className="candidate-entry-reason-grid"><div><h4>{t('candidate.entry.whyNow')}</h4>{entry.why_now_codes.map((code) => <p key={code}>+ {entryCode(t, code)}</p>)}</div><div><h4>{t('candidate.entry.counter')}</h4>{entry.counterevidence_codes.map((code) => <p key={code}>− {entryCode(t, code)}</p>)}</div><div><h4>{t('candidate.entry.reviewable')}</h4>{entry.what_would_make_reviewable_codes.map((code) => <p key={code}>→ {entryCode(t, code)}</p>)}</div></div>
    </section> : null}
    <section><h3>{t('candidate.contributionTitle')}</h3><div className="candidate-contributions">{item.components.map((component) => <div key={component.component_id}><span>{componentName(t, component.component_id)}</span><div><i style={{ width: `${Math.max(0, Math.min(100, Number(component.score ?? 0)))}%` }} /></div><strong>{component.contribution ?? '—'}</strong></div>)}</div></section>
    <section className="candidate-evidence-grid"><div><h3>{t('candidate.supporting')}</h3>{supports.map((row) => <p key={`${row.evidence_id}-${row.component_id}`}>+ {componentName(t, row.component_id)}{row.observed_value ? ` · ${row.observed_value}` : ''}</p>)}</div><div><h3>{t('candidate.counter')}</h3>{counters.map((row) => <p key={`${row.evidence_id}-${row.component_id}`}>− {componentName(t, row.component_id)}{row.observed_value ? ` · ${row.observed_value}` : ''}</p>)}</div></section>
    <section><h3>{t('candidate.invalidation')}</h3><ul>{item.invalidation_condition_codes.map((code) => <li key={code}>{t(`candidate.invalidation.${code}` as never)}</li>)}</ul></section>
    <section><h3>{t('candidate.rawFacts')}</h3><div className="candidate-facts"><span>{t('candidate.liquidity')} <strong>{money(item.median_dollar_volume_20)}</strong></span><span>{t('candidate.volatility')} <strong>{percent(item.annualized_volatility_10)}</strong></span><span>{t('candidate.maxGap')} <strong>{percent(item.maximum_absolute_open_gap_5)}</strong></span><span>{t('candidate.volumeRatio')} <strong>{number(item.current_volume_ratio, 2)}×</strong></span><span>{t('candidate.etfProxy')} <strong>{item.primary_driver_ticker ?? '—'}</strong></span><span>{t('common.correlation')} <strong>{number(item.driver_correlation_20, 2)}</strong></span></div></section>
    <section><h3>{t('candidate.manualChecks')}</h3><p>{t('candidate.manualChecksBody')}</p></section>
  </aside></div>;
}

function StrategyDetail({ item, parameterFingerprint, onClose }: { item: StrategyAssessment; parameterFingerprint: string; onClose: () => void }): JSX.Element {
  const { t } = useI18n();
  const extension = item.evidence.find((row) => row.evidence_id === 'entry_extension_risk');
  const supports = item.evidence.filter((row) => row.evidence_kind === 'supporting' && row.availability === 'available' && row.evidence_id !== 'entry_extension_risk');
  const counters = item.evidence.filter((row) => row.evidence_kind === 'counterevidence' && row.availability === 'available' && row.evidence_id !== 'entry_extension_risk');
  const contributions = strategyScoreBreakdown(item, parameterFingerprint);
  useEffect(() => { const key = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key); }, [onClose]);
  return <div className="candidate-drawer-backdrop" role="presentation" onMouseDown={(event) => { if (event.currentTarget === event.target) onClose(); }}><aside className="candidate-drawer strategy-drawer" role="dialog" aria-modal="true" aria-labelledby="strategy-detail-title">
    <header><div><p className="eyebrow">{t('candidate.strategy.detailEyebrow')}</p><h2 id="strategy-detail-title">{item.ticker} · {strategyChannelName(t, item.channel)}</h2><p>{item.instrument_id} · {item.security_type}</p></div><button type="button" onClick={onClose} aria-label={t('common.close')}>×</button></header>
    <div className="candidate-detail-summary"><div><span>{t('candidate.strategy.status')}</span><strong>{strategyStatusName(t, item.status)}</strong></div><div><span>{t('candidate.strategy.score')}</span><strong>{number(item.channel_score)}</strong></div><div><span>{t('candidate.strategy.rank')}</span><strong>#{item.within_channel_rank}</strong></div><div><span>{t('candidate.strategy.marketFit')}</span><strong>{t(`candidate.strategy.marketFit.${item.market_fit}` as never)}</strong></div></div>
    <p className="candidate-boundary">{t('candidate.strategy.boundary')}</p>
    {extension ? <section className="strategy-location-fact"><span>{t('candidate.strategy.positionRisk')}</span><strong>{strategyEvidenceValue(t, extension)}</strong><small>{t('candidate.strategy.positionRiskBody')}</small></section> : null}
    <section className="strategy-contribution-section"><h3>{t('candidate.strategy.contributionTitle')}</h3><p>{t('candidate.strategy.contributionBody')}</p><div className="strategy-contribution-table"><div className="strategy-contribution-head"><span>{t('candidate.strategy.component')}</span><span>{t('candidate.strategy.inputScore')}</span><span>{t('candidate.strategy.weight')}</span><span>{t('candidate.strategy.contribution')}</span></div>{contributions.map((row) => <div key={row.component_id}><strong>{strategyComponentName(t, row.component_id)}</strong><span>{number(row.input_score)}</span><span>{(row.weight_bps / 100).toFixed(0)}%</span><span><i style={{ width: `${Math.min(100, Number(row.contribution))}%` }} />{number(row.contribution)}</span></div>)}</div><small>{t('candidate.strategy.formulaVerified')}</small></section>
    <section className="strategy-decision-grid"><div><h3>{t('candidate.strategy.why')}</h3>{item.why_surfaced_codes.map((code) => <p key={code}>+ {strategyCode(t, code)}</p>)}</div><div><h3>{t('candidate.strategy.firstRisk')}</h3><p>− {strategyCode(t, item.first_rejection_code)}</p></div><div><h3>{t('candidate.strategy.next')}</h3>{item.what_would_make_researchable_codes.length ? item.what_would_make_researchable_codes.map((code) => <p key={code}>→ {strategyCode(t, code)}</p>) : <p>→ {t('candidate.strategy.advanceNext')}</p>}</div></section>
    <section className="candidate-evidence-grid"><div><h3>{t('candidate.supporting')}</h3>{supports.map((row) => <p key={row.evidence_id}>+ {strategyEvidenceName(t, row)} · {strategyEvidenceValue(t, row)}</p>)}</div><div><h3>{t('candidate.counter')}</h3>{counters.map((row) => <p key={row.evidence_id}>− {strategyEvidenceName(t, row)} · {strategyEvidenceValue(t, row)}</p>)}</div></section>
    <section><h3>{t('candidate.strategy.invalidation')}</h3><ul>{item.invalidation_codes.map((code) => <li key={code}>{strategyCode(t, code)}</li>)}</ul></section>
    <section><h3>{t('candidate.manualChecks')}</h3><ul>{item.required_manual_check_codes.map((code) => <li key={code}>{strategyCode(t, code)}</li>)}</ul></section>
    <details className="candidate-boundary-details"><summary>{t('candidate.strategy.boundaries')}</summary><ul>{[...new Set([...item.market_fit_reason_codes, ...item.missing_required_evidence_codes, ...item.warning_codes])].map((code) => <li key={code}>{strategyCode(t, code)}</li>)}</ul></details>
  </aside></div>;
}

function StrategyWorkspace({ state, channel, setChannel, openDetail }: { state: StrategyLoadState; channel: StrategyChannel; setChannel: (value: StrategyChannel) => void; openDetail: (item: StrategyAssessment) => void }): JSX.Element {
  const { t } = useI18n();
  if (state.kind === 'idle' || state.kind === 'loading') return <section className="panel state-panel">{t('candidate.strategy.loading')}</section>;
  if (state.kind === 'error') return <section className="panel state-panel error-state" role="alert"><h2>{t('candidate.strategy.unavailable')}</h2><p>{localizeClientError(t, state.message)}</p><p>{t('candidate.failClosed')}</p></section>;
  const selected = state.data.universe.channels.find((item) => item.channel === channel)!;
  const parameterFingerprint = state.data.source.strategy_parameter_fingerprint;
  const method = strategyMethod(channel, parameterFingerprint);
  return <><section className="candidate-axis-explainer strategy-boundary"><div><span>{t('candidate.strategy.sameChannel')}</span><strong>{t('candidate.strategy.sameChannelBody')}</strong></div><b>≠</b><div><span>{t('candidate.strategy.tradeDecision')}</span><strong>{t('candidate.strategy.tradeDecisionBody')}</strong></div><p>{t('candidate.strategy.unvalidated')}</p></section>
    <section className="strategy-channel-grid">{state.data.universe.channels.map((item) => { const unavailableOnly = item.qualifying_count === 0 && (item.status_counts.deprioritized ?? 0) === 0 && (item.status_counts.unavailable ?? 0) > 0; return <button type="button" key={item.channel} aria-pressed={channel === item.channel} className={`strategy-channel-card ${channel === item.channel ? 'active' : ''} ${unavailableOnly ? 'unavailable' : ''}`} onClick={() => setChannel(item.channel)}><span>{strategyChannelName(t, item.channel)}</span><strong>{unavailableOnly ? t('common.unavailable') : item.qualifying_count.toLocaleString('en-US')}</strong><small>{unavailableOnly ? `${t('candidate.strategy.evidencePending')} · ${(item.status_counts.unavailable ?? 0).toLocaleString('en-US')}` : `${t('candidate.strategy.advanceShort')} ${item.status_counts.advance_to_research ?? 0} · ${t('candidate.strategy.watchShort')} ${item.status_counts.watch_for_trigger ?? 0}`}</small></button>; })}</section>
    <section className="panel candidate-summary"><h2>{strategyChannelName(t, channel)}</h2><p>{t(`candidate.strategy.channelBody.${channel}` as never)}</p><div><span>{t('candidate.strategy.advance')} <strong>{selected.status_counts.advance_to_research ?? 0}</strong></span><span>{t('candidate.strategy.watch')} <strong>{selected.status_counts.watch_for_trigger ?? 0}</strong></span><span>{t('candidate.strategy.deprioritized')} <strong>{selected.status_counts.deprioritized ?? 0}</strong></span><span>{t('common.unavailable')} <strong>{selected.status_counts.unavailable ?? 0}</strong></span></div></section>
    {method ? <details className="panel methodology strategy-methodology"><summary>{t('candidate.strategy.formulaTitle')}</summary><p>{t('candidate.strategy.formulaIntro')}</p><p className="strategy-distinctness-warning">{t('candidate.strategy.distinctnessWarning')}</p><div className="strategy-formula-grid">{method.components.map((component) => <div key={component.component_id}><strong>{strategyComponentName(t, component.component_id)}</strong><span>{(component.weight_bps / 100).toFixed(0)}%</span></div>)}</div><h3>{t('candidate.strategy.componentLogicTitle')}</h3><div className="strategy-component-logic">{method.components.filter((component) => component.component_id !== 'entry_geometry').map((component) => <div key={component.component_id}><strong>{strategyComponentName(t, component.component_id)}</strong><p>{t(`candidate.strategy.componentLogic.${component.component_id}` as never)}</p></div>)}</div><h3>{t('candidate.strategy.statusRules')}</h3><p>{t(`candidate.strategy.statusRule.${method.status_rule}` as never)}</p><h3>{t('candidate.strategy.geometryMapping')}</h3><div className="strategy-geometry-grid">{Object.entries(method.geometry_scores).map(([setup, score]) => <span key={setup}>{setupName(t, setup as CandidateTechnicalSetup)} <strong>{number(score)}</strong></span>)}</div><h3>{t('candidate.strategy.rankingRule')}</h3><p>{t('candidate.strategy.rankingRuleBody')}</p><small>{t('candidate.strategy.formulaSource')}</small><code>{parameterFingerprint}</code></details> : null}
    {selected.displayed_records.length ? <section className="panel strategy-results"><div className="strategy-result-head"><span>{t('candidate.strategy.rank')}</span><span>{t('candidate.symbol')}</span><span>{t('candidate.strategy.status')}</span><span>{t('candidate.strategy.score')}</span><span>{t('candidate.strategy.why')}</span><span>{t('candidate.strategy.firstRisk')}</span></div>{selected.displayed_records.map((item) => <button type="button" className="strategy-result-row" key={item.instrument_id} onClick={() => openDetail(item)}><strong>#{item.within_channel_rank}</strong><span><strong>{item.ticker}</strong><small>{item.security_type}</small></span><span className={`strategy-status strategy-status-${item.status}`}>{strategyStatusName(t, item.status)}</span><strong>{number(item.channel_score)}</strong><span>{strategyCode(t, item.why_surfaced_codes[0])}</span><span>{strategyCode(t, item.first_rejection_code)}</span></button>)}</section> : <section className="panel candidate-empty"><h3>{t('candidate.strategy.noDisplay')}</h3><p>{t(`candidate.strategy.unavailableBody.${channel}` as never)}</p></section>}
    <details className="panel methodology"><summary>{t('candidate.methodTitle')}</summary><p>{t('candidate.strategy.method')}</p><code>{state.data.logical_fingerprint}</code></details></>;
}

export function OpportunityCandidatesPage(): JSX.Element {
  const { t } = useI18n(); const [universe, setUniverse] = useState(requestedUniverse); const [mode, setMode] = useState<CandidateRiskMode>(requestedMode);
  const detailController = useRef<AbortController | null>(null);
  const [state, setState] = useState<LoadState>({ kind: 'loading' }); const [stage, setStage] = useState<StageFilter>('active'); const [search, setSearch] = useState(''); const [selected, setSelected] = useState<CandidateItem | null>(null); const [detailLoading, setDetailLoading] = useState(false); const [detailError, setDetailError] = useState(''); const [view, setView] = useState<CandidateView>(requestedView); const [lane, setLane] = useState<CandidateEntryLane>('review_now');
  const [strategyState, setStrategyState] = useState<StrategyLoadState>({ kind: 'idle' }); const [strategyChannel, setStrategyChannel] = useState<StrategyChannel>(requestedStrategyChannel); const [strategySelected, setStrategySelected] = useState<StrategyAssessment | null>(null);
  const load = useCallback((universeId: string) => { const controller = new AbortController(); detailController.current?.abort(); detailController.current = null; setState({ kind: 'loading' }); setSelected(null); setStrategySelected(null); setStrategyState({ kind: 'idle' }); setDetailLoading(false); setDetailError(''); getOpportunityCandidates(universeId, controller.signal).then((data) => { setState({ kind: 'ready', data }); setView((current) => current === 'strategy' && !data.strategy_available ? (data.universe.entry_risk_modes ? 'entry' : 'leadership') : current === 'entry' && !data.universe.entry_risk_modes ? 'leadership' : current); }).catch((error: unknown) => { if (!controller.signal.aborted) setState({ kind: 'error', message: error instanceof Error ? error.message : '' }); }); return () => controller.abort(); }, []);
  useEffect(() => { const cancelLoad = load(universe); return () => { cancelLoad(); detailController.current?.abort(); }; }, [load, universe]); useEffect(() => { const pop = () => { setUniverse(requestedUniverse()); setMode(requestedMode()); setView(requestedView()); setStrategyChannel(requestedStrategyChannel()); }; window.addEventListener('popstate', pop); return () => window.removeEventListener('popstate', pop); }, []);
  useEffect(() => { if (view !== 'strategy' || state.kind !== 'ready' || !state.data.strategy_available) return undefined; const controller = new AbortController(); setStrategySelected(null); setStrategyState({ kind: 'loading' }); import('../api/candidateStrategies').then(({ getCandidateStrategies }) => getCandidateStrategies(universe, controller.signal)).then((data) => { if (!controller.signal.aborted) setStrategyState({ kind: 'ready', data }); }).catch((error: unknown) => { if (!controller.signal.aborted) setStrategyState({ kind: 'error', message: error instanceof Error ? error.message : '' }); }); return () => controller.abort(); }, [state, universe, view]);
  const rows = useMemo(() => { if (state.kind !== 'ready') return []; const result = state.data.universe.risk_modes.find((row) => row.risk_mode === mode); const formalOrder = new Map((result?.displayed_instrument_ids ?? []).map((id, index) => [id, index + 1])); const entryMode = state.data.universe.entry_risk_modes?.find((row) => row.risk_mode === mode); const entryLane = entryMode?.lanes.find((row) => row.lane === lane); const entryOrder = new Map((entryLane?.displayed_instrument_ids ?? []).map((id, index) => [id, index + 1])); return state.data.universe.candidates.filter((item) => {
    if (view === 'entry') return entryOrder.has(item.instrument_id);
    if (stage === 'active') return formalOrder.has(item.instrument_id) && ['watch', 'prepare', 'enter'].includes(item.state.final_stage ?? '');
    if (stage === 'all') return true;
    return item.state.final_stage === stage;
  }).filter((item) => item.ticker.toLowerCase().includes(search.trim().toLowerCase())).sort((a, b) => (view === 'entry' ? (entryOrder.get(a.instrument_id) ?? 9999) - (entryOrder.get(b.instrument_id) ?? 9999) : (formalOrder.get(a.instrument_id) ?? 9999) - (formalOrder.get(b.instrument_id) ?? 9999)) || Number(b.base_score ?? 0) - Number(a.base_score ?? 0)); }, [lane, mode, search, stage, state, view]);
  if (state.kind === 'loading') return <main className="app-shell candidate-shell"><div className="panel state-panel">{t('candidate.loading')}</div></main>;
  if (state.kind === 'error') return <main className="app-shell candidate-shell"><div className="panel state-panel error-state" role="alert"><h1>{t('candidate.unavailable')}</h1><p>{localizeClientError(t, state.message)}</p><p>{t('candidate.failClosed')}</p><button type="button" onClick={() => load(universe)}>{t('common.retry')}</button></div></main>;
  const data = state.data; const risk = data.universe.risk_modes.find((row) => row.risk_mode === mode)!; const entryMode = data.universe.entry_risk_modes?.find((row) => row.risk_mode === mode); const selectedLane = entryMode?.lanes.find((row) => row.lane === lane);
  const selectedStrategyChannel = strategyState.kind === 'ready' ? strategyState.data.universe.channels.find((item) => item.channel === strategyChannel) : undefined;
  const selectView = (value: CandidateView): void => { setView(value); writeQuery('candidateView', value); };
  const selectStrategyChannel = (value: StrategyChannel): void => { setStrategyChannel(value); writeQuery('candidateStrategy', value); };
  const openDetail = (item: CandidateListItem): void => { detailController.current?.abort(); const controller = new AbortController(); detailController.current = controller; setSelected(null); setDetailError(''); setDetailLoading(true); getOpportunityCandidateDetail(data, item, controller.signal).then((detail) => { if (detailController.current === controller) { detailController.current = null; setSelected(detail); setDetailLoading(false); } }).catch((error: unknown) => { if (!controller.signal.aborted && detailController.current === controller) { detailController.current = null; setDetailLoading(false); setDetailError(error instanceof Error ? error.message : ''); } }); };
  return <main className="app-shell candidate-shell"><section className="candidate-hero"><p className="eyebrow">{t('candidate.eyebrow')}</p><h1>{t('candidate.title')}</h1><p>{t('candidate.subtitleV2')}</p><div className="candidate-hero-facts"><span>{t('common.asOf')} <strong>{data.as_of_session}</strong></span><span>{universeName(t, data.selected_universe_id)} <strong>{data.universe.universe_member_count.toLocaleString('en-US')}</strong></span><span>{view === 'strategy' ? t('candidate.strategy.qualifying') : t('candidate.hardQualified')} <strong>{view === 'strategy' ? selectedStrategyChannel?.qualifying_count.toLocaleString('en-US') ?? '—' : entryMode?.hard_risk_gate_qualified_count ?? risk.eligible_count}</strong></span><span>{t('candidate.displayed')} <strong>{view === 'strategy' ? selectedStrategyChannel?.displayed_records.length ?? '—' : rows.length}</strong></span></div></section>
    <section className="panel candidate-control-panel"><div className="candidate-view-tabs"><button type="button" aria-pressed={view === 'entry'} className={view === 'entry' ? 'active' : ''} disabled={!entryMode} onClick={() => selectView('entry')}>{t('candidate.entry.view')}</button><button type="button" aria-pressed={view === 'leadership'} className={view === 'leadership' ? 'active' : ''} onClick={() => selectView('leadership')}>{t('candidate.leadership.view')}</button>{data.strategy_available ? <button type="button" aria-pressed={view === 'strategy'} className={view === 'strategy' ? 'active' : ''} onClick={() => selectView('strategy')}>{t('candidate.strategy.view')}</button> : null}</div>{view === 'strategy' ? <p className="candidate-strategy-control-note">{t('candidate.strategy.riskIndependent')}</p> : <><div className="candidate-risk-tabs" aria-label={t('candidate.riskMode')}>{MODES.map((value) => <button type="button" className={mode === value ? 'active' : ''} key={value} onClick={() => { setMode(value); writeQuery('candidateRisk', value); }}>{t(`candidate.risk.${value}` as never)}</button>)}</div><p>{t('candidate.riskExplanationV2')}</p></>}<div className="candidate-filters">{view === 'leadership' ? <label>{t('common.state')}<select value={stage} onChange={(event) => setStage(event.target.value as StageFilter)}><option value="active">{t('candidate.filter.active')}</option><option value="watch">{t('candidate.stage.watch')}</option><option value="prepare">{t('candidate.stage.prepare')}</option><option value="enter">{t('candidate.stage.enter')}</option><option value="invalidated">{t('candidate.stage.invalidated')}</option><option value="all">{t('candidate.filter.all')}</option></select></label> : null}{view !== 'strategy' ? <label>{t('candidate.search')}<input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="AAPL" /></label> : null}</div></section>
    {view === 'strategy' ? <StrategyWorkspace state={strategyState} channel={strategyChannel} setChannel={selectStrategyChannel} openDetail={setStrategySelected} /> : <>
    {view === 'entry' && entryMode ? <><section className="candidate-axis-explainer"><div><span>{t('candidate.axis.quality')}</span><strong>{t('candidate.axis.qualityBody')}</strong></div><b>×</b><div><span>{t('candidate.axis.location')}</span><strong>{t('candidate.axis.locationBody')}</strong></div><p>{t('candidate.axis.boundary')}</p></section><section className="candidate-lanes">{entryMode.lanes.map((item) => <button type="button" key={item.lane} className={`candidate-lane-card candidate-lane-${item.lane} ${lane === item.lane ? 'active' : ''}`} onClick={() => setLane(item.lane)}><span>{laneName(t, item.lane)}</span><strong>{item.qualifying_count.toLocaleString('en-US')}</strong><small>{t('candidate.entry.showing')} {item.displayed_instrument_ids.length}/{item.display_cap}</small><i style={{ width: `${Math.min(100, item.qualifying_count / Math.max(1, entryMode.hard_risk_gate_qualified_count) * 100)}%` }} /></button>)}</section></> : null}
    <section className="panel candidate-summary"><h2>{view === 'entry' ? laneName(t, lane) : t('candidate.currentState')}</h2>{view === 'entry' ? <p>{t(`candidate.entry.laneBody.${lane}` as never)}</p> : <><div><span>{t('candidate.stage.watch')} <strong>{data.universe.stage_counts.watch ?? 0}</strong></span><span>{t('candidate.stage.prepare')} <strong>{data.universe.stage_counts.prepare ?? 0}</strong></span><span>{t('candidate.stage.enter')} <strong>{data.universe.stage_counts.enter ?? 0}</strong></span><span>{t('candidate.stage.invalidated')} <strong>{data.universe.stage_counts.invalidated ?? 0}</strong></span><span>{t('candidate.manualReview')} <strong>{data.universe.stage_counts.unavailable ?? 0}</strong></span></div><p>{t('candidate.shortHistory')}</p></>}</section>
    <section className={`panel candidate-board ${view === 'entry' ? 'candidate-board-entry' : ''}`}><div className="candidate-table-head"><span>{view === 'entry' ? t('candidate.entry.order') : t('candidate.rank')}</span><span>{t('candidate.symbol')}</span><span>{view === 'entry' ? t('candidate.entry.location') : t('common.state')}</span><span>{view === 'entry' ? t('candidate.entry.structure') : t('candidate.baseScore')}</span><span>{view === 'entry' ? t('candidate.entry.extensionLabel') : t('candidate.dataSupport')}</span><span>{t('candidate.baseScore')}</span><span>{view === 'entry' ? t('candidate.entry.supportDistance') : t('candidate.liquidity')}</span><span>{view === 'entry' ? t('candidate.formalRank') : t('candidate.quality')}</span></div>{rows.map((item, index) => { const disposition = item.risk_dispositions.find((row) => row.risk_mode === mode)!; const entry = item.entry_geometry ?? item.entry_summary; const supportDistance = item.entry_geometry?.metrics.reference_support_distance_pct ?? item.entry_summary?.reference_support_distance_pct ?? null; return <button type="button" className="candidate-row" key={item.instrument_id} onClick={() => openDetail(item)}><strong>#{view === 'entry' ? index + 1 : disposition.risk_adjusted_rank ?? '—'}</strong><span><strong>{item.ticker}</strong><small>{item.security_type}</small></span><span className={view === 'entry' && entry ? `candidate-entry-posture candidate-entry-posture-${entry.review_posture}` : `candidate-stage candidate-stage-${item.state.final_stage ?? 'unavailable'}`}>{view === 'entry' && entry ? postureName(t, entry.review_posture) : stageName(t, item.state.final_stage)}</span><strong>{view === 'entry' && entry ? setupName(t, entry.technical_setup) : number(item.base_score)}</strong><span>{view === 'entry' && entry ? extensionName(t, entry.extension_risk) : percent(item.confidence.confidence)}</span><strong>{number(item.base_score)}</strong><span>{view === 'entry' && entry ? percent(supportDistance) : money(item.median_dollar_volume_20)}</span><span>{disposition.risk_adjusted_rank ? `#${disposition.risk_adjusted_rank}` : t('candidate.entry.fullPool')}</span></button>; })}{rows.length === 0 ? <div className="candidate-empty"><h3>{t('candidate.empty')}</h3><p>{view === 'entry' && selectedLane?.qualifying_count === 0 ? t('candidate.entry.noQualified') : t('candidate.emptyBody')}</p></div> : null}</section>
    <details className="panel methodology"><summary>{t('candidate.methodTitle')}</summary><p>{t('candidate.methodBodyV2')}</p><code>{data.logical_fingerprint}</code></details></>}
    {selected ? <CandidateDetail item={selected} mode={mode} onClose={() => setSelected(null)} /> : null}
    {strategySelected && strategyState.kind === 'ready' ? <StrategyDetail item={strategySelected} parameterFingerprint={strategyState.data.source.strategy_parameter_fingerprint} onClose={() => setStrategySelected(null)} /> : null}
    {detailLoading ? <div className="candidate-drawer-backdrop"><aside className="candidate-drawer" role="status"><div className="panel state-panel">{t('candidate.loading')}</div></aside></div> : null}
    {detailError ? <div className="candidate-drawer-backdrop" role="presentation" onMouseDown={(event) => { if (event.currentTarget === event.target) setDetailError(''); }}><aside className="candidate-drawer" role="alert"><header><h2>{t('candidate.unavailable')}</h2><button type="button" onClick={() => setDetailError('')} aria-label={t('common.close')}>×</button></header><p>{localizeClientError(t, detailError)}</p><p>{t('candidate.failClosed')}</p></aside></div> : null}
  </main>;
}
