import { cleanup, render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { I18nProvider } from '../i18n/I18nProvider';
import { QuantResearchLabPage } from './QuantResearchLabPage';

describe('Quant Research Lab', () => {
  beforeEach(() => {
    window.localStorage.clear();
    window.history.replaceState({}, '', '/dashboard/?lang=en&view=research');
  });
  afterEach(cleanup);

  it('shows the closed V2 Development screen and next governed boundary without implying an active model', async () => {
    const user = userEvent.setup();
    render(<I18nProvider><QuantResearchLabPage /></I18nProvider>);
    expect(screen.getByRole('heading', { name: 'Quant Research Lab' })).toBeInTheDocument();
    expect(screen.getByText('FACTOR DISCOVERY V2')).toBeInTheDocument();
    expect(screen.getByText('CLOSED · NO CANDIDATE ALPHA')).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: 'From measurement to a decision—without collapsing the evidence.' })).toBeInTheDocument();
    expect(screen.getByText('Factor Discovery').parentElement).toHaveTextContent('CURRENT · V2 CLOSED');
    expect(screen.getByText('Model Construction').parentElement).toHaveTextContent('LOCKED');
    expect(screen.getByText('Strategy Expression').parentElement).toHaveTextContent('LOCKED');
    expect(screen.getByText(/A factor is not a model/)).toBeInTheDocument();
    expect(screen.getByText(/Submit a falsifiable factor or strategy hypothesis/)).toBeInTheDocument();
    expect(screen.getByRole('link', { name: 'Contact · @whalphalab' })).toHaveAttribute('href', 'https://x.com/whalphalab');
    expect(screen.getByRole('heading', { name: 'Renewable factor-discovery loop' })).toBeInTheDocument();
    expect(screen.getByText('Operating mode').parentElement).toHaveTextContent('RENEWABLE');
    expect(screen.getByText('Current stage').parentElement).toHaveTextContent('HYPOTHESIS INTAKE');
    expect(screen.getByText('Completed campaigns').parentElement).toHaveTextContent('2');
    expect(screen.getByText('Formal trials consumed').parentElement).toHaveTextContent('14');
    expect(screen.getByText('Current position').parentElement).toHaveTextContent('READY FOR A NEW QUESTION');
    expect(screen.getByText('Why the loop continues').parentElement).toHaveTextContent('FAILURE DOES NOT END DISCOVERY');
    expect(screen.getByRole('heading', { name: 'Stage-isolated research team' })).toBeInTheDocument();
    expect(screen.getByText('Market-state qualification').parentElement).toHaveTextContent('PASSED · 267 / 287');
    expect(screen.getByText('Exact replay').parentElement).toHaveTextContent('MATCHED');
    expect(screen.getByText(/02 · Market-state qualification/).parentElement).toHaveTextContent('COMPLETED');
    expect(screen.getByText(/not an unattended Alpha miner/i)).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: 'Evidence ladder' })).toBeInTheDocument();
    expect(screen.getByText('Three-layer architecture').parentElement).toHaveTextContent('ACCEPTED');
    expect(screen.getByText('Cumulative research ledger').parentElement).toHaveTextContent('CLOSED · 14 TRIALS');
    expect(screen.getAllByText('Factor Catalog V2')[0].parentElement).toHaveTextContent('SCREENED');
    expect(screen.getByText('V2 data qualification').parentElement).toHaveTextContent('PASSED');
    expect(screen.getByText('Development screen').parentElement).toHaveTextContent('COMPLETED');
    expect(screen.getByText('Exact reproduction').parentElement).toHaveTextContent('VERIFIED');
    expect(screen.getByText('Next discovery campaign').parentElement).toHaveTextContent('DESIGN BOUNDARY');
    expect(screen.getByText('Model, strategy & Product').parentElement).toHaveTextContent('LOCKED');
    expect(screen.getByRole('heading', { name: 'Research foundation snapshot' })).toBeInTheDocument();
    expect(screen.getByText('Five-year market base').parentElement).toHaveTextContent('1,255');
    expect(screen.getByText('Historical membership').parentElement).toHaveTextContent('RECONSTRUCTED');
    expect(screen.getByText('Lifecycle & terminal').parentElement).toHaveTextContent('219 + 83');
    expect(screen.getByText(/not blended into one readiness percentage/i)).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: 'Factor qualification V2' })).toBeInTheDocument();
    expect(screen.getByText('98.59%')).toBeInTheDocument();
    expect(screen.getByText('Complete vectors').parentElement).toHaveTextContent('431,249');
    expect(screen.getByText('Pair checks').parentElement).toHaveTextContent('28');
    expect(screen.getByText('Near-duplicate groups').parentElement).toHaveTextContent('0');
    expect(screen.getByText(/No pair met the full near-duplicate rule/i)).toBeInTheDocument();
    expect(screen.getByText('What V2 earned').parentElement).toHaveTextContent('8 / 8 eligible for protocol review');
    expect(screen.getByText('Qualification outcome').parentElement).toHaveTextContent('SCREEN COMPLETED · SEE DECISION BELOW');
    expect(screen.getByRole('heading', { name: 'Completed Development Screen · Factor Catalog V2' })).toBeInTheDocument();
    expect(screen.getByText('Formal trials').parentElement).toHaveTextContent('6');
    expect(screen.getByText('Cumulative trials').parentElement).toHaveTextContent('14');
    expect(screen.getAllByText('Signal sessions')[0].parentElement).toHaveTextContent('106');
    expect(screen.getAllByText('Observations')[0].parentElement).toHaveTextContent('167,860');
    expect(screen.getAllByText('Forward labels')[0].parentElement).toHaveTextContent('503,580');
    expect(screen.getByText('Candidate Alpha decision').parentElement).toHaveTextContent('0 / 4 admitted');
    expect(screen.getByText('Risk evidence').parentElement).toHaveTextContent('2 qualified · 0 selected');
    expect(screen.getAllByText('Risk evidence · not selected')).toHaveLength(2);
    expect(screen.getByText('Next governed question').parentElement).toHaveTextContent('NEW FACTOR BATCH · NOT YET REGISTERED');
    expect(screen.getByRole('heading', { name: 'Historical Development Screen · Factor Catalog V1' })).toBeInTheDocument();
    expect(screen.getByText('Formal hypotheses').parentElement).toHaveTextContent('8');
    expect(screen.getAllByText('Forward labels')[1].parentElement).toHaveTextContent('503,580');
    expect(screen.getByText('The honest result').parentElement).toHaveTextContent('0 / 5 Alpha');
    expect(screen.getByText('Risk guard retained')).toBeInTheDocument();
    expect(screen.getAllByText('Rejected')).toHaveLength(11);
    expect(screen.getByRole('heading', { name: 'Historical method-engineering evidence' })).toBeInTheDocument();
    expect(screen.getByText('95.38%')).toBeInTheDocument();
    expect(screen.getByText('Declared paths').parentElement).toHaveTextContent('437,402');
    expect(screen.getByText('Computable paths').parentElement).toHaveTextContent('417,209');
    expect(screen.getByText(/not win rate, prediction accuracy, or return/i)).toBeInTheDocument();
    expect(screen.getByText(/only registered replacement was rejected/i)).toBeInTheDocument();
    expect(screen.getByText('Strong-Leader Pullback')).toBeInTheDocument();
    expect(screen.getByText('Not Candidate-eligible')).toBeInTheDocument();
    expect(screen.getAllByText('Factor Catalog V2')[1].parentElement).toHaveTextContent('Closed · no candidate Alpha');
    expect(screen.getByText('Active models').parentElement).toHaveTextContent('None');
    expect(screen.queryByText(/win\/payoff\/PF/i)).not.toBeNull();
    expect(screen.queryByText(/annualized return/i)).not.toBeInTheDocument();

    await user.click(screen.getByText(/Inspect deduplication, budget/));
    expect(screen.getByText('Duplicate identity')).toBeInTheDocument();
    expect(screen.queryByText('55c1eaccbd5ef5c8ef6dd695c4e4e010ed0e11c6483e55f1a2ce6b70898f8218')).not.toBeInTheDocument();

    await user.click(screen.getByText(/Inspect complete logic/));
    expect(screen.getByText(/max\(close\[t-20:t-1\]\)/)).toBeInTheDocument();
    expect(screen.queryByText('4622fb2fe86cc28249f53c89003f450a9e9d19c5696cd4eb865f413140b982c8')).not.toBeInTheDocument();

    await user.click(screen.getByText(/Inspect all eight registered definitions/));
    expect(screen.getAllByText('126-session relative momentum, skipping the latest five')).toHaveLength(3);
    expect(screen.getByText('ln(C[t-5]/C[t-126]) - ln(B[t-5]/B[t-126])')).toBeInTheDocument();
    expect(screen.queryByText('b74214155cc148d1e0d37c530ab4fea2f385af1a81237b901eec45e1fee2eb0b')).not.toBeInTheDocument();

    await user.click(screen.getByText(/Inspect the frozen protocol, lineage/));
    expect(screen.getAllByText('126-session relative momentum, skipping the latest five')).toHaveLength(3);
    expect(screen.queryByText('5441468ef8b392f555aac5a4e9cc8c6d50a9fb064349b6da342ccc2540dc193b')).not.toBeInTheDocument();

    await user.click(screen.getByText(/Inspect protocol, custody, limits/));
    expect(screen.queryByText('5e40cd9ab11dd20a98aabdf0834dc3cfb5c5a173a94929eca73891db8f8f789a')).not.toBeInTheDocument();
  });

  it('renders the complete research boundary in Chinese', () => {
    window.history.replaceState({}, '', '/dashboard/?lang=zh&view=research');
    render(<I18nProvider><QuantResearchLabPage /></I18nProvider>);
    expect(screen.getByRole('heading', { name: '量化研究实验室' })).toBeInTheDocument();
    expect(screen.getByText('因子发现 V2')).toBeInTheDocument();
    expect(screen.getAllByText('已关闭 · 无候选 Alpha')[0]).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: '从测量到决策，每一层证据都保持独立。' })).toBeInTheDocument();
    expect(screen.getByText('因子发现层').parentElement).toHaveTextContent('当前阶段 · V2 已关闭');
    expect(screen.getByText('模型构建层').parentElement).toHaveTextContent('保持锁定');
    expect(screen.getByText('策略表达层').parentElement).toHaveTextContent('保持锁定');
    expect(screen.getByRole('heading', { name: '可持续因子发现循环' })).toBeInTheDocument();
    expect(screen.getByText(/欢迎提交可证伪的因子或策略假设/)).toBeInTheDocument();
    expect(screen.getByRole('link', { name: '联系 · @whalphalab' })).toHaveAttribute('href', 'https://x.com/whalphalab');
    expect(screen.getByText('运行模式').parentElement).toHaveTextContent('持续循环');
    expect(screen.getByText('当前位置').parentElement).toHaveTextContent('可以开始提出新问题');
    expect(screen.getByRole('heading', { name: '阶段隔离的研究协作组' })).toBeInTheDocument();
    expect(screen.getByText('市场状态资格').parentElement).toHaveTextContent('通过 · 267 / 287');
    expect(screen.getByText(/02 · 市场状态资格审查/).parentElement).toHaveTextContent('已完成');
    expect(screen.getByText(/不是无人监管的 Alpha 挖掘器/)).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: '证据阶梯' })).toBeInTheDocument();
    expect(screen.getByText('三层研究架构').parentElement).toHaveTextContent('已生效');
    expect(screen.getByText('累计研究账本').parentElement).toHaveTextContent('已关闭 · 共14项试验');
    expect(screen.getAllByText('因子目录 V2')[0].parentElement).toHaveTextContent('已筛选');
    expect(screen.getByText('V2 数据资格诊断').parentElement).toHaveTextContent('已通过');
    expect(screen.getByText('开发期筛选').parentElement).toHaveTextContent('已完成');
    expect(screen.getByText('精确复现').parentElement).toHaveTextContent('已验证');
    expect(screen.getByText('下一批因子发现').parentElement).toHaveTextContent('设计边界');
    expect(screen.getByRole('heading', { name: '研究基础快照' })).toBeInTheDocument();
    expect(screen.getByText('公司行动').parentElement).toHaveTextContent('4,623 / 4,643');
    expect(screen.getByText(/不会把不同证据强行合成为一个“总完成度”/)).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: '因子资格诊断 V2' })).toBeInTheDocument();
    expect(screen.getByText('完整向量').parentElement).toHaveTextContent('431,249');
    expect(screen.getByText(/不代表存在预测价值/)).toBeInTheDocument();
    expect(screen.getByText('V2 获得了什么资格').parentElement).toHaveTextContent('8 / 8 项可进入协议审查');
    expect(screen.getByRole('heading', { name: '已完成开发期筛选 · 因子目录 V2' })).toBeInTheDocument();
    expect(screen.getByText('正式试验').parentElement).toHaveTextContent('6');
    expect(screen.getByText('累计试验').parentElement).toHaveTextContent('14');
    expect(screen.getByText('候选 Alpha 结论').parentElement).toHaveTextContent('0 / 4 获准');
    expect(screen.getByText('风险证据').parentElement).toHaveTextContent('2项通过 · 0项入选');
    expect(screen.getByRole('heading', { name: '历史开发期筛选 · 因子目录 V1' })).toBeInTheDocument();
    expect(screen.getByText('真实结论').parentElement).toHaveTextContent('0 / 5 Alpha');
    expect(screen.getByText('保留风险护栏')).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: '历史方法工程证据' })).toBeInTheDocument();
    expect(screen.getByText(/不是胜率、预测准确率或收益率/)).toBeInTheDocument();
    expect(screen.getByText('强势股回撤')).toBeInTheDocument();
    expect(screen.getByText('不可进入个股候选')).toBeInTheDocument();
    expect(screen.getByText(/股票证据不等于期权表现/)).toBeInTheDocument();
  });

  it('renders natural quantitative-research terminology in Spanish', () => {
    window.history.replaceState({}, '', '/dashboard/?lang=es&view=research');
    render(<I18nProvider><QuantResearchLabPage /></I18nProvider>);
    expect(screen.getByRole('heading', { name: 'Laboratorio de investigación cuantitativa' })).toBeInTheDocument();
    expect(screen.getByText('DESCUBRIMIENTO DE FACTORES V2')).toBeInTheDocument();
    expect(screen.getByText('CERRADO · SIN ALPHA CANDIDATO')).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: 'De la medición a la decisión, sin mezclar las capas de evidencia.' })).toBeInTheDocument();
    expect(screen.getAllByText('Descubrimiento de factores')[0].parentElement).toHaveTextContent('FASE ACTUAL · V2 CERRADO');
    expect(screen.getAllByText('Construcción del modelo')[0].parentElement).toHaveTextContent('BLOQUEADA');
    expect(screen.getAllByText('Expresión de estrategia')[0].parentElement).toHaveTextContent('BLOQUEADA');
    expect(screen.getByRole('heading', { name: 'Ciclo renovable de descubrimiento de factores' })).toBeInTheDocument();
    expect(screen.getByText(/Se aceptan hipótesis refutables de factores o estrategias/)).toBeInTheDocument();
    expect(screen.getByRole('link', { name: 'Contacto · @whalphalab' })).toHaveAttribute('href', 'https://x.com/whalphalab');
    expect(screen.getByText('Modo operativo').parentElement).toHaveTextContent('RENOVABLE');
    expect(screen.getByText('Posición actual').parentElement).toHaveTextContent('LISTO PARA UNA NUEVA PREGUNTA');
    expect(screen.getByRole('heading', { name: 'Equipo de investigación aislado por etapas' })).toBeInTheDocument();
    expect(screen.getByText('Calificación de mercado').parentElement).toHaveTextContent('SUPERADA · 267 / 287');
    expect(screen.getByText(/02 · Calificación del estado de mercado/).parentElement).toHaveTextContent('COMPLETADA');
    expect(screen.getByText(/No es un minero de Alpha autónomo/)).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: 'Escalera de evidencia' })).toBeInTheDocument();
    expect(screen.getByText('Arquitectura de tres capas').parentElement).toHaveTextContent('ACEPTADA');
    expect(screen.getByText('Registro acumulativo de investigación').parentElement).toHaveTextContent('CERRADO · 14 PRUEBAS');
    expect(screen.getAllByText('Catálogo de factores V2')[0].parentElement).toHaveTextContent('EVALUADO');
    expect(screen.getByText('Calificación de datos V2').parentElement).toHaveTextContent('SUPERADA');
    expect(screen.getByText('Selección en Desarrollo').parentElement).toHaveTextContent('COMPLETADA');
    expect(screen.getAllByText('Reproducción exacta')[1].parentElement).toHaveTextContent('VERIFICADA');
    expect(screen.getByRole('heading', { name: 'Resumen de la base de investigación' })).toBeInTheDocument();
    expect(screen.getByText('Ciclo de vida y terminal').parentElement).toHaveTextContent('219 + 83');
    expect(screen.getByText(/no se combinan en un único porcentaje de avance/)).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: 'Calificación de factores V2' })).toBeInTheDocument();
    expect(screen.getByText('Vectores completos').parentElement).toHaveTextContent('431.249');
    expect(screen.getByRole('heading', { name: 'Selección de Desarrollo completada · Catálogo V2' })).toBeInTheDocument();
    expect(screen.getByText('Pruebas formales').parentElement).toHaveTextContent('6');
    expect(screen.getByText('Pruebas acumuladas').parentElement).toHaveTextContent('14');
    expect(screen.getByRole('heading', { name: 'Selección histórica en Desarrollo · Catálogo V1' })).toBeInTheDocument();
    expect(screen.getByText('Salvaguarda conservada')).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: 'Evidencia histórica de ingeniería' })).toBeInTheDocument();
    expect(screen.getByText(/no es tasa de acierto, precisión predictiva ni rentabilidad/)).toBeInTheDocument();
    expect(screen.getByText('No apto para Candidatos')).toBeInTheDocument();
    expect(screen.getByText(/La evidencia de una acción no es rendimiento de opciones/)).toBeInTheDocument();
  });
});
